---
language: python
python: "2.7"
env:
  #- ANSIBLE_VERSION=1.4
  #- ANSIBLE_VERSION=1.5
  #- ANSIBLE_VERSION=1.6
  #- ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.8
before_install:
 - sudo apt-get update -qq
install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  #- "printf '[defaults]\\nroles_path = ../' > ansible.cfg"

  # Install dependencies.
  #- ansible-galaxy install geerlingguy.mysql
  #- ansible-galaxy install geerlingguy.apache
  #- ansible-galaxy install geerlingguy.php
  #- ansible-galaxy install geerlingguy.php-mysql
  #- ansible-galaxy install geerlingguy.phpmyadmin
  #- git clone https://github.com/Stouts/Stouts.python.git python
  #- git clone https://github.com/debops/ansible-role-ansible.git ansible
  #- git clone https://github.com/geerlingguy/ansible-role-ntp.git geerlingguy.ntp
  #- git clone https://github.com/AlbanAndrieu/ansible-locale.git locale
  #- git clone https://github.com/AlbanAndrieu/ansible-hostname.git alban.andrieu.hostname
  #- git clone https://github.com/AlbanAndrieu/ansible-java.git java
  #- git clone https://github.com/AlbanAndrieu/ansible-common.git alban.andrieu.common
  #- git clone https://github.com/AlbanAndrieu/ansible-pagespeed.git alban.andrieu.pagespeed
  - git clone https://github.com/AlbanAndrieu/ansible-galaxy.ubuntu.virtualbox.git virtualbox
  - git clone https://github.com/geerlingguy/ansible-role-apache.git geerlingguy.apache
  - git clone https://github.com/geerlingguy/ansible-role-phpmyadmin.git geerlingguy.phpmyadmin
  - git clone https://github.com/geerlingguy/ansible-role-mysql.git geerlingguy.mysql
  - git clone https://github.com/geerlingguy/ansible-role-php-mysql.git geerlingguy.php-mysql
  - git clone https://github.com/geerlingguy/ansible-role-php.git geerlingguy.php
script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i hosts phpvirtualbox.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i hosts phpvirtualbox.yml --connection=local --sudo -vvvv

  # Run the role/playbook again, checking to make sure it's idempotent.
  # - >
  #   ansible-playbook -i hosts phpvirtualbox.yml --connection=local --sudo
  #   | grep -q 'changed=0.*failed=0'
  #   && (echo 'Idempotence test: pass' && exit 0)
  #   || (echo 'Idempotence test: fail' && exit 1)
