---

- name: PhpVirtualbox | Mysql | Create database for each site
  mysql_db: >
    name={{ phpvirtualbox_db_name }}
    state=present
    login_host={{ phpvirtualbox_db_host }}
    login_user={{ phpvirtualbox_db_user}}
    login_password={{ phpvirtualbox_db_password }}
  register: phpvirtualbox_mysql_db_create

- name: PhpVirtualbox | Mysql | Copy saved database to server
  copy: >
    src={{ phpvirtualbox_database_backup }}
    dest=/tmp/{{ phpvirtualbox_site_name }}.sql
    login_user={{ phpvirtualbox_db_user}}
    login_password={{ phpvirtualbox_db_password }}
  when: phpvirtualbox_mysql_site_restore_saved_db|bool

- name: PhpVirtualbox | Mysql | Import saved database
  mysql_db: >
    name={{ phpvirtualbox_db_name }}
    state=import
    target=/tmp/{{ phpvirtualbox_site_name }}.sql
    login_host={{ phpvirtualbox_db_host }}
    login_user={{ phpvirtualbox_db_user}}
    login_password={{ phpvirtualbox_db_password }}
  when: phpvirtualbox_mysql_site_restore_saved_db|bool

- name: PhpVirtualbox | Mysql | Create/assign database user to db and grant permissions
  mysql_user: >
    name={{ phpvirtualbox_db_user }}
    password={{ phpvirtualbox_db_password }}
    priv='{{ phpvirtualbox_db_name }}.*:ALL'
    state=present
    login_host={{ phpvirtualbox_db_host }}
    login_user={{ phpvirtualbox_db_user}}
    login_password={{ phpvirtualbox_db_password }}
